import path from "path";

export const generatedDir = path.resolve("./generated");
export const typedocDir = path.join(generatedDir, "typedoc");
export const typedocTypesDir = path.join(typedocDir, "types");
export const hooksDocsDir = "./docs/hooks"

export const autoGeneratedNotice = `# This file was automatically generated.
# Any manual modifications made to this file will not be retained.
# Changes will be overwritten the next time this file is regenerated.`;
