
import fs from "fs-extra";

import { generateDocFiles } from "./utils/generate-doc-files";
import {
  findTsFilesSync,
  getFileNameWithoutExtension,
  readFile,
  removeMDLinks,
} from "./utils/utils";
import { autoGeneratedNotice, generatedDir, hooksDocsDir, typedocDir } from "./utils/consts";

const tsFiles = findTsFilesSync("./hooks").filter(
  (filePath) => !filePath.endsWith("index.ts")
);
console.log(tsFiles);

fs.ensureDirSync(hooksDocsDir)
const hooksData = tsFiles.map((hookFile) => {
  console.log(hookFile);
  return generateDocFiles(hookFile, getFileNameWithoutExtension(hookFile));
});

const featureItems = hooksData.map(
  (hData) => `
  - title: ${hData.hookName}
    details: ${removeMDLinks(hData.desc)}
    link: /hooks/${hData.slug}
`
);

fs.writeFileSync(
  "./docs/hooks/index.md",
  readFile("./scripts/temp-index.md")
    .replace("# <--features", featureItems.join(""))
    .replace("# <--notice", autoGeneratedNotice),
  "utf-8"
);
